# Generated by Django 5.1.3 on 2024-11-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_remove_todo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.CharField(default=1, max_length=350),
            preserve_default=False,
        ),
    ]
