# Generated by Django 5.1.3 on 2024-11-13 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_todo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deadline_at',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
